services:
  - type: web
    name: air_text
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails server -p $PORT"
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY_BASE
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: RAILS_ENV
        value: production
      - key: WEB_CONCURRENCY
        value: 2
